# Generated by Django 4.2.1 on 2023-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
