# Generated by Django 4.2.1 on 2023-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
