# Generated by Django 4.2.1 on 2023-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cliente_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
