# Generated by Django 4.2.1 on 2023-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cliente_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=6)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
